# Generated by Django 5.0.6 on 2024-05-11 16:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='article',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 57, 50, 195697, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Название Статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 57, 50, 195697, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-pub_date'], name='articles_ar_pub_dat_5d5d91_idx'),
        ),
    ]
